Repository devblogs-ir/InventoryStrategy, pull requests merged in 2024-01, with the labels that each got.

#7 Feat/hamidreza rahmani
  sources/hamidreza-rahmani/ConsoleApp/ConsoleApp.csproj
  sources/hamidreza-rahmani/ConsoleApp/Enumerators/FIFOEnumerator.cs
  sources/hamidreza-rahmani/ConsoleApp/Enumerators/LIFOEnumerator.cs
  sources/hamidreza-rahmani/ConsoleApp/InventoryWrapper.cs
  sources/hamidreza-rahmani/ConsoleApp/Models/InventoryManagementApproach.cs
  sources/hamidreza-rahmani/ConsoleApp/Models/Product.cs
  sources/hamidreza-rahmani/ConsoleApp/Program.cs
Labels: ** ready to review **

#11 feat: Implementing LIFO and FIFO
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy.sln
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/ConsoleApp.csproj
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/ConsoleApp.sln
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/InventoryWrapper.cs
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/Models/InventoryManagementApproach.cs
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/Models/Product.cs
  sources/ZahraLiaghatmand/InventoryStrategy/InventoryStrategy/Program.cs
Labels: ** ready to review **

#10 Feat/arvin mashayekhi
  sources/Arvin-Mashayekhi/InventoryStrategy.sln
  sources/Arvin-Mashayekhi/InventoryStrategy/Entities/InventoryManagementApproach.cs
  sources/Arvin-Mashayekhi/InventoryStrategy/Entities/Product.cs
  sources/Arvin-Mashayekhi/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Arvin-Mashayekhi/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Arvin-Mashayekhi/InventoryStrategy/InventoryStrategy.csproj
  sources/Arvin-Mashayekhi/InventoryStrategy/InventoryWrapper.cs
  sources/Arvin-Mashayekhi/InventoryStrategy/Program.cs
Labels: ** ready to review **, ** need some changes **

#22 Add FIFO and LIFO approaches to InventoryStrategy project
  sources/Morvarid Arab/ConsoleApp/ConsoleApp.csproj
  sources/Morvarid Arab/ConsoleApp/Enumerators/FIFOEnumerator.cs
  sources/Morvarid Arab/ConsoleApp/Enumerators/LIFOEnumerator.cs
  sources/Morvarid Arab/ConsoleApp/InventoryWrapper.cs
  sources/Morvarid Arab/ConsoleApp/Models/InventoryManagementApproach.cs
  sources/Morvarid Arab/ConsoleApp/Models/Product.cs
  sources/Morvarid Arab/ConsoleApp/Program.cs
  sources/Morvarid Arab/README.md
  sources/Morvarid Arab/dotnet-tests.sln
Labels: ** ready to review **

#18 Implemented IEnumerators and IEnumerable
  sources/Nazanin-Abbasi/InventoryStrategy/InventoryStrategy.sln
  template/ConsoleApp/Enumerators/FIFOEnumerator.cs
  template/ConsoleApp/Enumerators/LIFOEnumerator.cs
  template/ConsoleApp/InventoryWrapper.cs
  template/ConsoleApp/Program.cs
Labels: ** ready to review **

#16 LIFO and FIFO implemented
  .editorconfig
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy.sln
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Enumerators/BaseEnuemrator.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/InventoryStrategy.csproj
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/InventoryWrapper.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Models/InventoryManagementApproach.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Models/Product.cs
  sources/Mohmmad-Jebelli/InventoryStrategy/InventoryStrategy/Program.cs
Labels: ** ready to review **

#13 Implemented Inventory Strategy
  sources/Niloo Mont/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Niloo Mont/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Niloo Mont/InventoryStrategy/InventoryStrategy.csproj
  sources/Niloo Mont/InventoryStrategy/InventoryStrategy.sln
  sources/Niloo Mont/InventoryStrategy/InventoryWrapper.cs
  sources/Niloo Mont/InventoryStrategy/Models/Enums/InventoryManagementApproach.cs
  sources/Niloo Mont/InventoryStrategy/Models/Phone.cs
  sources/Niloo Mont/InventoryStrategy/Models/Product.cs
  sources/Niloo Mont/InventoryStrategy/Models/TV.cs
  sources/Niloo Mont/InventoryStrategy/Models/Tablet.cs
  sources/Niloo Mont/InventoryStrategy/Program.cs
  sources/Niloo Mont/README.md
Labels: ** ready to review **

#20 FIFO & LIFO implemented
  sources/mohammad-zarei/InventoryStrategy.sln
  sources/mohammad-zarei/src/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/mohammad-zarei/src/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/mohammad-zarei/src/InventoryStrategy/InventoryStrategy.csproj
  sources/mohammad-zarei/src/InventoryStrategy/InventoryWrapper.cs
  sources/mohammad-zarei/src/InventoryStrategy/Models/InventoryManagementApproach.cs
  sources/mohammad-zarei/src/InventoryStrategy/Models/Product.cs
  sources/mohammad-zarei/src/InventoryStrategy/Program.cs
Labels: ** ready to review **

#14 feat: InventoryStrategy
  sources/Mehran-Minaei/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Mehran-Minaei/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Mehran-Minaei/InventoryStrategy/InventoryStrategy.csproj
  sources/Mehran-Minaei/InventoryStrategy/InventoryStrategy.sln
  sources/Mehran-Minaei/InventoryStrategy/InventoryWrapper.cs
  sources/Mehran-Minaei/InventoryStrategy/Models/InventoryManagementApproach.cs
  sources/Mehran-Minaei/InventoryStrategy/Models/Product.cs
  sources/Mehran-Minaei/InventoryStrategy/Program.cs
Labels: ** ready to review **

#17 create fifo and lifo methods
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/Enumerators/FIFOEnumerator.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/Enumerators/LIFOEnumerator.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/InventoryStrategy.ConsoleApp.csproj
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/InventoryWrapper.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/Models/InventoryManagementApproach.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/Models/Product.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.ConsoleApp/Program.cs
  sources/Alireza-Askari/InventoryStrategy/InventoryStrategy.sln
Labels: ** ready to review **

#24 Feat/amin afrasiabi
  sources/Amin Afrasiabi/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Amin Afrasiabi/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Amin Afrasiabi/InventoryStrategy/InventoryStrategy.csproj
  sources/Amin Afrasiabi/InventoryStrategy/InventoryStrategy.sln
  sources/Amin Afrasiabi/InventoryStrategy/InventoryWrapper.cs
  sources/Amin Afrasiabi/InventoryStrategy/Models/InventoryManagementApproach.cs
  sources/Amin Afrasiabi/InventoryStrategy/Models/Laptop.cs
  sources/Amin Afrasiabi/InventoryStrategy/Models/Mobile.cs
  sources/Amin Afrasiabi/InventoryStrategy/Models/Product.cs
  sources/Amin Afrasiabi/InventoryStrategy/Program.cs
  sources/Amin Afrasiabi/README.md
Labels: ** need some changes **

#25 Feat/amin afrasiabi
  sources/Amin Afrasiabi/InventoryStrategy/Enumerators/FIFOEnumerator.cs
  sources/Amin Afrasiabi/InventoryStrategy/Enumerators/LIFOEnumerator.cs
  sources/Amin Afrasiabi/InventoryStrategy/InventoryWrapper.cs
  sources/Amin Afrasiabi/InventoryStrategy/Program.cs
Labels: ** ready to review **
